<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "votable"
 *
 * Auto generated by Extension Builder 2015-12-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Versatile and pluggable Voting system',
	'description' => 'Declare a content type to be votable in your `ext_tables`, create a content element votable on a page and your Frontend Users can vote...',
	'category' => 'plugin',
	'author' => 'Udriot Fabien, Lorenz Ulrich',
	'author_email' => 'fabien@omic.ch, lorenz.ulrich@visol.ch>',
	'state' => 'beta',
	'version' => '0.9.0-dev',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'vidi' => '',
		),
	),
);